subinclude("//build_defs:postgres")

postgres(
    name="postgres",
    version="18.0",
    _compress=True,
)

postgres_ai(
    name="postgres_ai",
    version="18.0",
    pgvector_version="0.8.2",
    age_version="1.7.0-rc0",
    age_pg_major="PG18",
    _compress=True,
)
