subinclude("//build_defs:postgres")

postgres(
    name="postgres",
    version="14.19",
    _compress=True,
)

postgres_ai(
    name="postgres_ai",
    version="14.19",
    age_version="1.6.0-rc0",
    age_pg_major="PG14",
    _compress=True,
)
