subinclude("///shell//build_defs:shell")

sh_test(
    name = "contrib_test",
    src = "test_contrib.sh",
    size = "large",
    sandbox = False,
)

sh_test(
    name = "ai_test",
    src = "test_ai.sh",
    size = "large",
    sandbox = False,
)
