subinclude("//build_defs:postgres")

postgres(
    name="postgres",
    version="15.14",
    _compress=True,
)

postgres_ai(
    name="postgres_ai",
    version="15.14",
    age_version="1.6.0-rc0",
    age_pg_major="PG15",
    _compress=True,
)
