subinclude("//build_defs:postgres")

postgres(
    name="postgres",
    version="17.0",
    _compress=True,
)

postgres_ai(
    name="postgres_ai",
    version="17.0",
    age_version="1.6.0-rc0",
    age_pg_major="PG17",
    _compress=True,
)
