subinclude("//build_defs:postgres")

postgres(
    name="postgres",
    version="13.22",
    _compress=True,
)

postgres_ai(
    name="postgres_ai",
    version="13.22",
    age_version="1.5.0-rc0",
    age_pg_major="PG13",
    _compress=True,
)
