subinclude("//build_defs:postgres")

postgres(
    name="postgres",
    version="16.10",
    _compress=True,
)

postgres_ai(
    name="postgres_ai",
    version="16.10",
    age_version="1.6.0-rc0",
    age_pg_major="PG16",
    _compress=True,
)
